import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { AssetKind, AssetStatus, ContentStatus, PartnerType, QuestionSourceType, QuestionStatus, QuestionType, Role, VideoProcessingStatus } from '../../common/types/roles.enum';
import { toPaginationMeta } from '../../common/dto/pagination-query.dto';
import type { RequestUser } from '../../common/types/request-with-user.types';
import { PrismaService } from '../../database/prisma.service';
import { paginateArabicSearch, sqlAnd } from '../../common/search/arabic-search';
import { contentStatusScope } from '../../common/search/content-scope';
import { AuditService } from '../audit/audit.service';
import { CreateQuestionBankDto, CreateQuestionDto, CreateQuestionOptionDto, CreateQuestionSourceDto, QueryQuestionBankDto, QueryQuestionDto, QueryQuestionSourceDto, QuestionPlacementDto, SetQuestionVideoLinkDto, UpdateQuestionBankDto, UpdateQuestionDto, UpdateQuestionOptionDto, UpdateQuestionSourceDto } from './dto/question-banks.dto';

@Injectable()
export class QuestionBanksService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) { }
  private admin(actor: RequestUser) { if (actor.role !== Role.ADMIN && actor.role !== Role.SUPER_ADMIN) throw new ForbiddenException('Forbidden'); }
  private async log(actor: RequestUser, action: string, targetType: string, targetId: string, metadata?: object) { await this.audit.record({ actorUserId: actor.id, action, targetType, targetId, metadata }); }
  private async publisher(type: QuestionSourceType, publisherUserId?: string | null) {
    if (type !== QuestionSourceType.CONTENT_PUBLISHER) { if (publisherUserId) throw new BadRequestException('publisherUserId is allowed only for CONTENT_PUBLISHER sources'); return null; }
    if (!publisherUserId) throw new BadRequestException('CONTENT_PUBLISHER source requires publisherUserId');
    const publisher = await this.prisma.partnerProfile.findUnique({ where: { userId: publisherUserId } });
    if (!publisher || publisher.partnerType !== PartnerType.CONTENT_PUBLISHER) throw new BadRequestException('publisherUserId must reference a CONTENT_PUBLISHER partner');
    return publisherUserId;
  }
  private async source(id: string) { const x = await this.prisma.questionSource.findUnique({ where: { id } }); if (!x) throw new NotFoundException('Question source not found'); return x; }
  private async bank(id: string) { const x = await this.prisma.questionBank.findUnique({ where: { id } }); if (!x) throw new NotFoundException('Question bank not found'); return x; }
  private async question(id: string) { const x = await this.prisma.question.findUnique({ where: { id }, include: { source: true, bank: true, course: { include: { subject: { include: { academicGrade: true } } } }, placements: true, options: { orderBy: { sortOrder: 'asc' } }, assets: { include: { asset: true }, orderBy: { sortOrder: 'asc' } }, videoLink: { include: { videoAsset: { include: { asset: true } } } } } }); if (!x) throw new NotFoundException('Question not found'); return x; }
  private editable(status: QuestionStatus) { if (status === QuestionStatus.PUBLISHED || status === QuestionStatus.ARCHIVED) throw new ConflictException('Published or archived questions cannot be edited'); }
  private async draftSource(id: string) { const item = await this.source(id); if (item.status !== ContentStatus.DRAFT) throw new ConflictException('Only draft records can be edited'); return item; }
  private async draftBank(id: string) { const item = await this.bank(id); if (item.status !== ContentStatus.DRAFT) throw new ConflictException('Only draft records can be edited'); return item; }

  async createSource(actor: RequestUser, dto: CreateQuestionSourceDto) { this.admin(actor); const publisherUserId = await this.publisher(dto.type, dto.publisherUserId); const item = await this.prisma.questionSource.create({ data: { type: dto.type, titleAr: dto.title.ar.trim(), titleEn: dto.title.en.trim(), noteAr: dto.note?.ar, noteEn: dto.note?.en, publisherUserId, createdById: actor.id, updatedById: actor.id } }); await this.log(actor, 'QUESTION_SOURCE_CREATED', 'QuestionSource', item.id, { type: item.type }); return this.sourceDto(item); }
  async listSources(actor: RequestUser, q: QueryQuestionSourceDto) { this.admin(actor); const where = { status: q.status ?? { not: ContentStatus.ARCHIVED }, type: q.type }; const { data, total } = await paginateArabicSearch({ prisma: this.prisma, delegate: this.prisma.questionSource, target: 'questionSource', q: q.q, scope: { where: sqlAnd(contentStatusScope(q.status), q.type ? Prisma.sql`t.type = ${q.type}::"QuestionSourceType"` : undefined) }, orderBySql: Prisma.sql`t."createdAt" DESC, t.id ASC`, orderBy: [{ createdAt: 'desc' }, { id: 'asc' }], where, page: q.page, limit: q.limit }); return { data: data.map((item) => this.sourceDto(item)), meta: toPaginationMeta(q.page, q.limit, total) }; }
  async getSource(actor: RequestUser, id: string) { this.admin(actor); return this.sourceDto(await this.source(id)); }
  async updateSource(actor: RequestUser, id: string, dto: UpdateQuestionSourceDto) { this.admin(actor); const old = await this.draftSource(id); const type = dto.type ?? old.type; const publisherUserId = await this.publisher(type, dto.publisherUserId === undefined ? old.publisherUserId : dto.publisherUserId); const item = await this.prisma.questionSource.update({ where: { id }, data: { type, titleAr: dto.title?.ar?.trim(), titleEn: dto.title?.en?.trim(), ...(dto.note === undefined ? {} : { noteAr: dto.note?.ar ?? null, noteEn: dto.note?.en ?? null }), publisherUserId, updatedById: actor.id } }); await this.log(actor, 'QUESTION_SOURCE_UPDATED', 'QuestionSource', id); return this.sourceDto(item); }
  async createBank(actor: RequestUser, dto: CreateQuestionBankDto) { this.admin(actor); const item = await this.prisma.questionBank.create({ data: { title: dto.title.trim(), description: dto.description, createdById: actor.id, updatedById: actor.id } }); await this.log(actor, 'QUESTION_BANK_CREATED', 'QuestionBank', item.id); return item; }
  async listBanks(actor: RequestUser, q: QueryQuestionBankDto) { this.admin(actor); const where = { status: q.status ?? { not: ContentStatus.ARCHIVED } }; const { data, total } = await paginateArabicSearch({ prisma: this.prisma, delegate: this.prisma.questionBank, target: 'questionBank', q: q.q, scope: { where: contentStatusScope(q.status) }, orderBySql: Prisma.sql`t."createdAt" DESC, t.id ASC`, orderBy: [{ createdAt: 'desc' }, { id: 'asc' }], where, page: q.page, limit: q.limit }); return { data, meta: toPaginationMeta(q.page, q.limit, total) }; }
  async getBank(actor: RequestUser, id: string) { this.admin(actor); return this.bank(id); }
  async updateBank(actor: RequestUser, id: string, dto: UpdateQuestionBankDto) { this.admin(actor); await this.draftBank(id); const item = await this.prisma.questionBank.update({ where: { id }, data: { title: dto.title?.trim(), description: dto.description, updatedById: actor.id } }); await this.log(actor, 'QUESTION_BANK_UPDATED', 'QuestionBank', id); return item; }
  async publishResource(actor: RequestUser, kind: 'source' | 'bank', id: string) { this.admin(actor); const item = kind === 'source' ? await this.draftSource(id) : await this.draftBank(id); const client: any = kind === 'source' ? this.prisma.questionSource : this.prisma.questionBank; const updated = await client.update({ where: { id }, data: { status: ContentStatus.PUBLISHED, publishedAt: new Date(), updatedById: actor.id } }); await this.log(actor, `QUESTION_${kind.toUpperCase()}_PUBLISHED`, kind === 'source' ? 'QuestionSource' : 'QuestionBank', item.id); return updated; }
  async archiveResource(actor: RequestUser, kind: 'source' | 'bank', id: string) { this.admin(actor); const item: any = kind === 'source' ? await this.source(id) : await this.bank(id); if (item.status === ContentStatus.ARCHIVED) throw new ConflictException('Record is already archived'); const count = await this.prisma.question.count({ where: { [kind === 'source' ? 'sourceId' : 'bankId']: id, status: QuestionStatus.PUBLISHED } }); if (count) throw new ConflictException('Cannot archive a source or bank with published questions'); const client: any = kind === 'source' ? this.prisma.questionSource : this.prisma.questionBank; const updated = await client.update({ where: { id }, data: { status: ContentStatus.ARCHIVED, archivedAt: new Date(), updatedById: actor.id } }); await this.log(actor, `QUESTION_${kind.toUpperCase()}_ARCHIVED`, kind === 'source' ? 'QuestionSource' : 'QuestionBank', id); return updated; }
  async restoreResource(actor: RequestUser, kind: 'source' | 'bank', id: string) { this.admin(actor); const client: any = kind === 'source' ? this.prisma.questionSource : this.prisma.questionBank; const updated = await client.updateMany({ where: { id, status: ContentStatus.ARCHIVED }, data: { status: ContentStatus.DRAFT, archivedAt: null, publishedAt: null, updatedById: actor.id } }); if (!updated.count) throw new ConflictException('Only archived records can be restored'); await this.log(actor, `QUESTION_${kind.toUpperCase()}_RESTORED`, kind === 'source' ? 'QuestionSource' : 'QuestionBank', id); return kind === 'source' ? this.source(id) : this.bank(id); }
  async deleteResource(actor: RequestUser, kind: 'source' | 'bank', id: string) { this.admin(actor); if (kind === 'source') await this.draftSource(id); else await this.draftBank(id); if (await this.prisma.question.count({ where: { [kind === 'source' ? 'sourceId' : 'bankId']: id } })) throw new ConflictException('Referenced source or bank cannot be deleted'); const client: any = kind === 'source' ? this.prisma.questionSource : this.prisma.questionBank; await client.delete({ where: { id } }); await this.log(actor, `QUESTION_${kind.toUpperCase()}_DELETED`, kind === 'source' ? 'QuestionSource' : 'QuestionBank', id); return { id, deleted: true }; }

  private async course(id: string) { const x = await this.prisma.course.findUnique({ where: { id } }); if (!x) throw new NotFoundException('Course not found'); if (x.status === ContentStatus.ARCHIVED) throw new ConflictException('Archived courses cannot be used'); return x; }
  private async placementData(courseId: string, placements: QuestionPlacementDto[]) {
    const seen = new Set<string>();
    for (const placement of placements) {
      const targets = Object.entries(placement).filter(([, value]) => Boolean(value));
      if (targets.length !== 1) throw new BadRequestException('Each question placement must have exactly one target');
      const [field, id] = targets[0] as [keyof QuestionPlacementDto, string]; const key = `${field}:${id}`;
      if (seen.has(key)) throw new BadRequestException('Question placements must be unique'); seen.add(key);
      const target: any = field === 'courseId' ? await this.prisma.course.findUnique({ where: { id } }) : field === 'chapterId' ? await this.prisma.chapter.findUnique({ where: { id } }) : field === 'lessonId' ? await this.prisma.lesson.findUnique({ where: { id }, include: { chapter: true } }) : await this.prisma.section.findUnique({ where: { id }, include: { lesson: { include: { chapter: true } } } });
      if (!target || target.status === ContentStatus.ARCHIVED) throw new NotFoundException(`Placement ${field} not found`);
      const resolvedCourseId = field === 'courseId' ? target.id : field === 'chapterId' ? target.courseId : field === 'lessonId' ? target.chapter.courseId : target.lesson.chapter.courseId;
      if (resolvedCourseId !== courseId) throw new BadRequestException('All question placements must belong to the question course');
    }
    return placements.map((placement) => ({ courseId: placement.courseId, chapterId: placement.chapterId, lessonId: placement.lessonId, sectionId: placement.sectionId }));
  }
  async createQuestion(actor: RequestUser, dto: CreateQuestionDto) { this.admin(actor); await Promise.all([this.source(dto.sourceId), this.bank(dto.bankId), this.course(dto.courseId)]); const placements = await this.placementData(dto.courseId, dto.placements); const item = await this.prisma.question.create({ data: { bankId: dto.bankId, sourceId: dto.sourceId, courseId: dto.courseId, type: dto.type ?? QuestionType.SINGLE_CHOICE, body: dto.body.trim(), explanation: dto.explanation, createdById: actor.id, updatedById: actor.id, placements: { create: placements } } }); await this.log(actor, 'QUESTION_CREATED', 'Question', item.id); return this.getQuestion(actor, item.id); }
  async listQuestions(actor: RequestUser, q: QueryQuestionDto) { this.admin(actor); const placementWhere = q.chapterId ? { chapterId: q.chapterId } : q.lessonId ? { lessonId: q.lessonId } : q.sectionId ? { sectionId: q.sectionId } : undefined; const where: any = { status: q.status ?? { not: QuestionStatus.ARCHIVED }, bankId: q.bankId, sourceId: q.sourceId, courseId: q.courseId, placements: placementWhere ? { some: placementWhere } : undefined, course: q.subjectId || q.academicGradeId ? { subject: { ...(q.subjectId ? { id: q.subjectId } : {}), ...(q.academicGradeId ? { academicGradeId: q.academicGradeId } : {}) } } : undefined, }; const include: any = { placements: true, options: { orderBy: { sortOrder: 'asc' } }, assets: { include: { asset: true }, orderBy: { sortOrder: 'asc' } }, videoLink: { include: { videoAsset: { include: { asset: true } } } } };
    const { data, total } = await paginateArabicSearch({
      prisma: this.prisma,
      delegate: this.prisma.question,
      target: 'question',
      q: q.q,
      scope: {
        where: sqlAnd(
          q.status ? Prisma.sql`t.status = ${q.status}::"QuestionStatus"` : Prisma.sql`t.status <> 'ARCHIVED'::"QuestionStatus"`,
          q.bankId ? Prisma.sql`t."bankId" = ${q.bankId}` : undefined,
          q.sourceId ? Prisma.sql`t."sourceId" = ${q.sourceId}` : undefined,
          q.courseId ? Prisma.sql`t."courseId" = ${q.courseId}` : undefined,
          placementWhere
            ? Prisma.sql`EXISTS (SELECT 1 FROM "QuestionPlacement" qp WHERE qp."questionId" = t.id AND ${Prisma.raw(`qp."${Object.keys(placementWhere)[0]}"`)} = ${Object.values(placementWhere)[0]})`
            : undefined,
          q.subjectId || q.academicGradeId
            ? Prisma.sql`EXISTS (SELECT 1 FROM "Course" c JOIN "Subject" s ON s.id = c."subjectId" WHERE c.id = t."courseId" ${q.subjectId ? Prisma.sql`AND s.id = ${q.subjectId}` : Prisma.empty} ${q.academicGradeId ? Prisma.sql`AND s."academicGradeId" = ${q.academicGradeId}` : Prisma.empty})`
            : undefined,
        ),
      },
      orderBySql: Prisma.sql`t."createdAt" DESC, t.id ASC`,
      orderBy: [{ createdAt: 'desc' }, { id: 'asc' }],
      where,
      args: { include },
      page: q.page,
      limit: q.limit,
    }); return { data: data.map((x) => this.adminDto(x)), meta: toPaginationMeta(q.page, q.limit, total) }; }
  async getQuestion(actor: RequestUser, id: string) { this.admin(actor); return this.adminDto(await this.question(id)); }
  async updateQuestion(actor: RequestUser, id: string, dto: UpdateQuestionDto) { this.admin(actor); const old = await this.question(id); this.editable(old.status); const courseId = dto.courseId ?? old.courseId; if (dto.courseId !== undefined || dto.placements !== undefined) { if (old.status !== QuestionStatus.DRAFT && old.status !== QuestionStatus.REJECTED) throw new ConflictException('Question scope can be changed only while draft or rejected'); if (dto.courseId !== undefined && !dto.placements) throw new BadRequestException('Changing a question course requires replacement placements'); await this.course(courseId); } const placements = dto.placements ? await this.placementData(courseId, dto.placements) : undefined; await Promise.all([this.source(dto.sourceId ?? old.sourceId), this.bank(dto.bankId ?? old.bankId)]); await this.prisma.question.update({ where: { id }, data: { bankId: dto.bankId, sourceId: dto.sourceId, courseId: dto.courseId, type: dto.type, body: dto.body?.trim(), explanation: dto.explanation, updatedById: actor.id, ...(placements ? { placements: { deleteMany: {}, create: placements } } : {}) } }); await this.log(actor, 'QUESTION_UPDATED', 'Question', id); return this.getQuestion(actor, id); }
  private async validate(question: Awaited<ReturnType<QuestionBanksService['question']>>) { const attachmentKinds: AssetKind[] = [AssetKind.IMAGE, AssetKind.PDF, AssetKind.DOCUMENT]; if (!question.body.trim() || !question.explanation?.trim()) throw new ConflictException('Question body and explanation are required'); if (question.source.status !== ContentStatus.PUBLISHED || question.bank.status !== ContentStatus.PUBLISHED) throw new ConflictException('Question source and bank must be published'); const correct = question.options.filter((x) => x.isCorrect).length; if (question.options.length < 2 || correct < 1 || (question.type === QuestionType.SINGLE_CHOICE && correct !== 1) || (question.type === QuestionType.MULTIPLE_CHOICE && correct < 2)) throw new ConflictException('Question options do not satisfy its answer type'); if (!question.placements.length) throw new ConflictException('Question requires a placement'); if ([question.course, question.course.subject, question.course.subject.academicGrade].some((node: any) => node.status !== ContentStatus.PUBLISHED)) throw new ConflictException('Question course ancestry must be published'); for (const reference of question.assets) if (reference.asset.status !== AssetStatus.READY || !attachmentKinds.includes(reference.asset.kind)) throw new ConflictException('Question attachments must be ready compatible assets'); const link = question.videoLink; if (link) { const asset = link.videoAsset.asset; if (asset.status !== AssetStatus.READY || asset.kind !== AssetKind.VIDEO || link.videoAsset.processingStatus !== VideoProcessingStatus.READY) throw new ConflictException('Question video must be ready'); const duration = link.videoAsset.durationSeconds; if (duration != null && link.timestampSeconds >= duration) throw new ConflictException('Question video timestamp is outside the video duration'); } }
  async submit(actor: RequestUser, id: string) { this.admin(actor); const item = await this.question(id); if (item.status !== QuestionStatus.DRAFT && item.status !== QuestionStatus.REJECTED) throw new ConflictException('Only draft or rejected questions can be submitted'); await this.validate(item); await this.prisma.question.update({ where: { id }, data: { status: QuestionStatus.IN_REVIEW, reviewNote: null, reviewedAt: null, reviewedById: null, updatedById: actor.id } }); await this.log(actor, 'QUESTION_SUBMITTED_FOR_REVIEW', 'Question', id); return this.getQuestion(actor, id); }
  async publishQuestion(actor: RequestUser, id: string) { this.admin(actor); const item = await this.question(id); if (item.status !== QuestionStatus.IN_REVIEW) throw new ConflictException('Only questions in review can be published'); await this.validate(item); await this.prisma.question.update({ where: { id }, data: { status: QuestionStatus.PUBLISHED, publishedAt: new Date(), archivedAt: null, reviewedAt: new Date(), reviewedById: actor.id, updatedById: actor.id } }); await this.log(actor, 'QUESTION_PUBLISHED', 'Question', id); return this.getQuestion(actor, id); }
  async rejectQuestion(actor: RequestUser, id: string, reviewNote: string) { this.admin(actor); const item = await this.question(id); if (item.status !== QuestionStatus.IN_REVIEW) throw new ConflictException('Only questions in review can be rejected'); await this.prisma.question.update({ where: { id }, data: { status: QuestionStatus.REJECTED, reviewNote: reviewNote.trim(), reviewedAt: new Date(), reviewedById: actor.id, updatedById: actor.id } }); await this.log(actor, 'QUESTION_REJECTED', 'Question', id); return this.getQuestion(actor, id); }
  async archiveQuestion(actor: RequestUser, id: string) { this.admin(actor); const item = await this.question(id); if (item.status === QuestionStatus.ARCHIVED) throw new ConflictException('Question is already archived'); await this.prisma.question.update({ where: { id }, data: { status: QuestionStatus.ARCHIVED, archivedAt: new Date(), updatedById: actor.id } }); await this.log(actor, 'QUESTION_ARCHIVED', 'Question', id); return this.getQuestion(actor, id); }
  async deleteQuestion(actor: RequestUser, id: string) { this.admin(actor); const item = await this.question(id); if (item.status !== QuestionStatus.DRAFT || item.options.length || item.assets.length || item.videoLink) throw new ConflictException('Only an unreferenced draft question can be deleted'); await this.prisma.question.delete({ where: { id } }); await this.log(actor, 'QUESTION_DELETED', 'Question', id); return { id, deleted: true }; }
  async addOption(actor: RequestUser, id: string, dto: CreateQuestionOptionDto) { this.admin(actor); const item = await this.question(id); this.editable(item.status); const created = await this.prisma.questionOption.create({ data: { questionId: id, body: dto.body.trim(), isCorrect: dto.isCorrect ?? false, sortOrder: item.options.length + 1 } }); await this.log(actor, 'QUESTION_OPTION_ADDED', 'Question', id, { optionId: created.id }); return this.getQuestion(actor, id); }
  async updateOption(actor: RequestUser, id: string, optionId: string, dto: UpdateQuestionOptionDto) { this.admin(actor); const item = await this.question(id); this.editable(item.status); const option = await this.prisma.questionOption.findFirst({ where: { id: optionId, questionId: id } }); if (!option) throw new NotFoundException('Question option not found'); await this.prisma.questionOption.update({ where: { id: optionId }, data: { body: dto.body?.trim(), isCorrect: dto.isCorrect } }); await this.log(actor, 'QUESTION_OPTION_UPDATED', 'Question', id, { optionId }); return this.getQuestion(actor, id); }
  async deleteOption(actor: RequestUser, id: string, optionId: string) { this.admin(actor); const item = await this.question(id); this.editable(item.status); const option = await this.prisma.questionOption.findFirst({ where: { id: optionId, questionId: id } }); if (!option) throw new NotFoundException('Question option not found'); await this.prisma.$transaction([this.prisma.questionOption.delete({ where: { id: optionId } }), this.prisma.questionOption.updateMany({ where: { questionId: id, sortOrder: { gt: option.sortOrder } }, data: { sortOrder: { decrement: 1 } } })]); await this.log(actor, 'QUESTION_OPTION_DELETED', 'Question', id, { optionId }); return this.getQuestion(actor, id); }
  async reorderOptions(actor: RequestUser, id: string, optionIds: string[]) { this.admin(actor); const item = await this.question(id); this.editable(item.status); if (item.options.length !== optionIds.length || new Set(optionIds).size !== optionIds.length || item.options.some((x) => !optionIds.includes(x.id))) throw new BadRequestException('optionIds must contain every option exactly once'); await this.prisma.$transaction(async (tx) => { for (let i = 0; i < item.options.length; i++) await tx.questionOption.update({ where: { id: item.options[i].id }, data: { sortOrder: 1000000 + i } }); for (let i = 0; i < optionIds.length; i++) await tx.questionOption.update({ where: { id: optionIds[i] }, data: { sortOrder: i + 1 } }); }); await this.log(actor, 'QUESTION_OPTIONS_REORDERED', 'Question', id); return this.getQuestion(actor, id); }
  async addAsset(actor: RequestUser, id: string, assetId: string) { this.admin(actor); const item = await this.question(id); this.editable(item.status); const attachmentKinds: AssetKind[] = [AssetKind.IMAGE, AssetKind.PDF, AssetKind.DOCUMENT]; const asset = await this.prisma.asset.findUnique({ where: { id: assetId } }); if (!asset || asset.status !== AssetStatus.READY || !attachmentKinds.includes(asset.kind)) throw new ConflictException('Attachment must be a ready image, PDF, or document'); await this.prisma.questionAsset.create({ data: { questionId: id, assetId, sortOrder: item.assets.length + 1 } }); await this.log(actor, 'QUESTION_ASSET_ADDED', 'Question', id, { assetId }); return this.getQuestion(actor, id); }
  async removeAsset(actor: RequestUser, id: string, assetId: string) { this.admin(actor); const item = await this.question(id); this.editable(item.status); const ref = await this.prisma.questionAsset.findUnique({ where: { questionId_assetId: { questionId: id, assetId } } }); if (!ref) throw new NotFoundException('Question attachment not found'); await this.prisma.$transaction([this.prisma.questionAsset.delete({ where: { id: ref.id } }), this.prisma.questionAsset.updateMany({ where: { questionId: id, sortOrder: { gt: ref.sortOrder } }, data: { sortOrder: { decrement: 1 } } })]); await this.log(actor, 'QUESTION_ASSET_REMOVED', 'Question', id, { assetId }); return this.getQuestion(actor, id); }
  async reorderAssets(actor: RequestUser, id: string, assetIds: string[]) { this.admin(actor); const item = await this.question(id); this.editable(item.status); if (item.assets.length !== assetIds.length || new Set(assetIds).size !== assetIds.length || item.assets.some((x) => !assetIds.includes(x.assetId))) throw new BadRequestException('assetIds must contain every attachment exactly once'); await this.prisma.$transaction(async (tx) => { for (let i = 0; i < item.assets.length; i++) await tx.questionAsset.update({ where: { id: item.assets[i].id }, data: { sortOrder: 1000000 + i } }); for (let i = 0; i < assetIds.length; i++) await tx.questionAsset.update({ where: { questionId_assetId: { questionId: id, assetId: assetIds[i] } }, data: { sortOrder: i + 1 } }); }); await this.log(actor, 'QUESTION_ASSETS_REORDERED', 'Question', id); return this.getQuestion(actor, id); }
  async setVideo(actor: RequestUser, id: string, dto: SetQuestionVideoLinkDto) { this.admin(actor); const item = await this.question(id); this.editable(item.status); const asset = await this.prisma.asset.findUnique({ where: { id: dto.videoAssetId }, include: { video: true } }); if (!asset || asset.kind !== AssetKind.VIDEO || asset.status !== AssetStatus.READY || asset.video?.processingStatus !== VideoProcessingStatus.READY) throw new ConflictException('Video must be ready'); if (asset.video.durationSeconds != null && dto.timestampSeconds >= asset.video.durationSeconds) throw new BadRequestException('Video timestamp is outside the video duration'); await this.prisma.questionVideoLink.upsert({ where: { questionId: id }, create: { questionId: id, videoAssetId: dto.videoAssetId, timestampSeconds: dto.timestampSeconds }, update: { videoAssetId: dto.videoAssetId, timestampSeconds: dto.timestampSeconds } }); await this.log(actor, 'QUESTION_VIDEO_SET', 'Question', id, { videoAssetId: dto.videoAssetId }); return this.getQuestion(actor, id); }
  async removeVideo(actor: RequestUser, id: string) { this.admin(actor); const item = await this.question(id); this.editable(item.status); await this.prisma.questionVideoLink.deleteMany({ where: { questionId: id } }); await this.log(actor, 'QUESTION_VIDEO_REMOVED', 'Question', id); return this.getQuestion(actor, id); }
  private sourceDto(x: any) { const { titleAr, titleEn, noteAr, noteEn, ...rest } = x; return { ...rest, title: { ar: titleAr, en: titleEn }, note: { ar: noteAr, en: noteEn } }; }
  private adminDto(x: any) { return { ...x, ...(x.source ? { source: this.sourceDto(x.source) } : {}), scope: { courseId: x.courseId, subjectId: x.course?.subjectId, academicGradeId: x.course?.subject?.academicGradeId }, placements: x.placements ?? [] }; }
}
